// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2IykMv1nwjExeJz4MYvDT_Npoa4u9wrc',
    appId: '1:728881389917:web:11ebeb5262212a316a48b4',
    messagingSenderId: '728881389917',
    projectId: 'flutterdb-50235',
    authDomain: 'flutterdb-50235.firebaseapp.com',
    storageBucket: 'flutterdb-50235.appspot.com',
    measurementId: 'G-JSC0XQQWLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO4JYssfzOzklk7OGWX-gp3IELOXkW2fs',
    appId: '1:728881389917:android:2bc0c42b97b7770a6a48b4',
    messagingSenderId: '728881389917',
    projectId: 'flutterdb-50235',
    storageBucket: 'flutterdb-50235.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtk7UAO0fuJEnkbDDKVbEl49qEN-Rdrto',
    appId: '1:728881389917:ios:4eca800a0c1ff0f56a48b4',
    messagingSenderId: '728881389917',
    projectId: 'flutterdb-50235',
    storageBucket: 'flutterdb-50235.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtk7UAO0fuJEnkbDDKVbEl49qEN-Rdrto',
    appId: '1:728881389917:ios:4eca800a0c1ff0f56a48b4',
    messagingSenderId: '728881389917',
    projectId: 'flutterdb-50235',
    storageBucket: 'flutterdb-50235.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2IykMv1nwjExeJz4MYvDT_Npoa4u9wrc',
    appId: '1:728881389917:web:980787d59e903a336a48b4',
    messagingSenderId: '728881389917',
    projectId: 'flutterdb-50235',
    authDomain: 'flutterdb-50235.firebaseapp.com',
    storageBucket: 'flutterdb-50235.appspot.com',
    measurementId: 'G-4E2TVTJJQT',
  );
}
